version: '3'

services:
  federation-service:
    build: .
    image: federation-service
    container_name: federation-service
    restart: unless-stopped
    networks: 
      - deployments_core
      - kafka_broker
    env_file:
      - src/.env
    ports:
      - 9999:9999
  
  comms:
    container_name: comms
    image: postgres:12
    networks: 
      - deployments_core
    env_file:
      - src/.env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  gql:
    image: hasura/graphql-engine:v2.0.0-alpha.1
    networks: 
      - deployments_core
    env_file:
      - src/.env
    ports:
      - "15003:8080"
    depends_on:
      - comms
    restart: always

  scheduler-db:
    container_name: scheduler-db
    networks: 
      - deployments_core
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

networks:
  deployments_core:
    external: true
  kafka_broker:
    external: true